### ISSUE TITLE
How to implement Live Record on existing controllers / scaffolds?

### ISSUE THREAD

**Issue by iraszl** [jrpolidario/live_record#6]
First, to test my environment, I cloned the example simple live record project and was able to run it successfully.

Next, I tried to implement Live Record on an existing Rails project, but having difficulty even though I followed every step carefully.

I'm getting this error when loading an index page:
```
Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at Function.Model.addCallback.Model.addCallback (create.self-6059ce0d5a69c9336a1c7a415e0d7a8f543e2fec9a50c7f2aece6d31c01c45be.js?body=1:429)
    at posts:103
```

My suspicion is that I'm missing some code that would've been created if I was generating the scaffold after Live Record was already installed. Is this possible? And if so, is there a way to add the missing code manually?

Any help would be highly appreciated!

**Comment by iraszl** [comment]
Never mind.

I had this piece of code in my view:
```
  var subscription = LiveRecord.Model.all.Post.subscribe();
  LiveRecord.Model.all.Post.addCallback('after:createOrUpdate', function() {
    console.log(this);
  })
```

Once I removed it, the page started working correctly. Thanks!

**Comment by jrpolidario** [comment]
@iraszl Apologies for the delayed response, as I was travelling in a long flight.

If you don't have a `Post` model, then I think I kinda remember this error would pop up (I probably should have gracefully handled this error to be more helpful instead; I'll take note of this, sorry).

However, if you have a `Post` model but this error still popped up, then there's most likely a bug in my code. I'll further investigate on this after afterwards and after I get the time.

Thanks for letting me know this. Cheers.
